apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-pki-pulp-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  volumeName: etc-pki-pulp-volume
