apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  name: mongodb
spec:
  replicas: 1
  selector:
    name: mongodb
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mongodb
      annotations:
        openshift.io/scc: privileged
    spec:
      containers:
      - image: mongodb
        imagePullPolicy: IfNotPresent
        name: mongodb
        resources: {}
        securityContext:
          privileged: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mongodb
      from:
        kind: ImageStreamTag
        name: mongodb:latest
    type: ImageChange
