apiVersion: v1
kind: Pod
metadata:
  name: prepare
  annotations:
    openshift.io/scc: privileged
spec:
  containers:
  - name: prepare
    image: base
    imagePullPolicy: Always
    command: ["bash",  "-c", "/setup.sh"]
    env:
      - name: QPID
        value: qpid.pulp.svc.cluster.local
      - name: DB
        value: db.pulp.svc.cluster.local
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - mountPath: /dev/log
      name: dev-log-volume
    - mountPath: /etc/pulp
      name: etc-pulp-volume
    - mountPath: /etc/pki/pulp
      name: etc-pki-pulp-volume
    - mountPath: /var/lib/pulp
      name: var-lib-pulp-volume
  restartPolicy: Never
  volumes:
    - name: dev-log-volume
      persistentVolumeClaim:
        claimName: dev-log-claim
    - name: etc-pulp-volume
      persistentVolumeClaim:
        claimName: etc-pulp-claim
    - name: etc-pki-pulp-volume
      persistentVolumeClaim:
        claimName: etc-pki-pulp-claim
    - name: var-lib-pulp-volume
      persistentVolumeClaim:
        claimName: var-lib-pulp-claim
