apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  name: pulpapi
spec:
  replicas: 1
  selector:
    name: pulpapi
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/scc: privileged
      creationTimestamp: null
      labels:
        name: pulpapi
    spec:
      containers:
      - image: apache:latest
        imagePullPolicy: IfNotPresent
        name: pulpapi
        resources: {}
        terminationMessagePath: /dev/termination-log
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/log/httpd
          name: pulpapi-volume
        - mountPath: /dev/log
          name: dev-log-volume
        - mountPath: /etc/pulp
          name: etc-pulp-volume
        - mountPath: /etc/pki/pulp
          name: etc-pki-pulp-volume
        - mountPath: /var/lib/pulp
          name: var-lib-pulp-volume
      restartPolicy: Never
      volumes:
        - name: pulpapi-volume
          persistentVolumeClaim:
            claimName: pulpapi-claim
        - name: dev-log-volume
          persistentVolumeClaim:
            claimName: dev-log-claim
        - name: etc-pulp-volume
          persistentVolumeClaim:
            claimName: etc-pulp-claim
        - name: etc-pki-pulp-volume
          persistentVolumeClaim:
            claimName: etc-pki-pulp-claim
        - name: var-lib-pulp-volume
          persistentVolumeClaim:
            claimName: var-lib-pulp-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - pulpapi
      from:
        kind: ImageStreamTag
        name: "apache:latest"
    type: ImageChange
