apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: qpid
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    name: qpid
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
