apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-lib-pulp-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: var-lib-pulp-volume
